const data = [
  `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris interdum sit amet purus quis scelerisque. Vivamus tempor eget diam non sollicitudin. Mauris porttitor pretium dui vel malesuada. Curabitur rutrum, dui nec aliquam mollis, neque felis luctus turpis, sed egestas odio lorem ac erat. Fusce imperdiet nibh id purus lobortis molestie. Quisque augue nibh, commodo nec elit vitae, dapibus dignissim lacus. Aliquam erat volutpat. Mauris vitae leo sed tortor facilisis porttitor. Vivamus at odio leo. Nam id dui et dui viverra faucibus. Proin ut lacus et ex vehicula vulputate et vel leo. Nam lobortis dolor sed purus ultricies molestie. Etiam placerat quam eget enim lobortis, fermentum vehicula sapien ullamcorper.`,
  `Curabitur id vehicula diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed at justo imperdiet, elementum elit sed, consectetur dolor. Vestibulum pharetra, magna eu finibus pellentesque, erat leo vulputate leo, fermentum tempor magna quam vitae lectus. Praesent maximus nec quam sit amet suscipit. Nulla viverra luctus sollicitudin. Aenean ultricies nisi in ullamcorper feugiat. Lorem ipsum dolor sit amet, consectetur adipiscing elit.`,
  `Suspendisse tincidunt tortor sit amet sollicitudin aliquam. Nulla maximus sem et iaculis iaculis. Suspendisse sit amet odio placerat, porta dolor et, mollis nisi. Nunc sem nisl, aliquam ut vehicula a, auctor ac nisl. Curabitur ultricies purus nisi, a ultricies tortor congue ut. Nulla facilisi. Suspendisse sed magna cursus, commodo nisi at, efficitur elit.

  `,
  `Donec consequat sed est non convallis. Maecenas maximus enim tempor, feugiat erat condimentum, varius dui. Duis volutpat viverra nisl iaculis aliquet. Proin pretium dui et lectus interdum, vitae efficitur ex rhoncus. Proin non dictum ipsum, sit amet dictum felis. Quisque a efficitur arcu. Sed viverra sed lacus quis vehicula. Morbi efficitur et metus eu feugiat. Mauris vitae tellus mattis, tempus nisl a, laoreet erat. Phasellus venenatis placerat dolor, ut feugiat enim volutpat non.`,
  `Aenean dapibus, magna sed maximus consectetur, erat purus gravida tortor, vitae mattis mauris urna id dui. Maecenas volutpat lacus tellus, nec bibendum nulla pulvinar eu. Aenean feugiat faucibus augue, a auctor nisl lobortis in. Fusce neque nibh, venenatis a massa at, maximus placerat enim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Etiam pulvinar quis erat id dapibus. Vivamus faucibus sollicitudin ullamcorper.`,
  `Suspendisse potenti. Vestibulum mattis, diam at rhoncus vestibulum, odio ante luctus enim, a egestas velit purus non mi. Phasellus sit amet convallis odio, eu rutrum lorem. Proin finibus diam erat, nec luctus neque accumsan a. Aliquam euismod velit sit amet purus condimentum rutrum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Pellentesque non accumsan neque.

  `,
  `Donec tempus nec sem vel dapibus. Cras quam metus, hendrerit vel convallis eget, convallis vel sem. Phasellus tellus nisl, viverra vel urna a, commodo faucibus turpis. Fusce varius eros sit amet varius posuere. In hac habitasse platea dictumst. Ut sit amet pharetra mi. Phasellus in lorem ut enim elementum lacinia. Vestibulum ac lacus id urna pellentesque venenatis. Nam eget eros dui. Proin id sagittis mi.`,
  `Nam imperdiet sit amet odio ut aliquam. Vestibulum semper dictum lectus, vitae interdum tortor varius eget. Cras vitae iaculis mi. Pellentesque mattis dignissim volutpat. Duis at ultricies turpis. Cras vitae iaculis lacus. Proin tincidunt gravida odio, non aliquet neque. Pellentesque ullamcorper commodo vestibulum. Praesent varius consectetur nunc, quis facilisis lorem convallis quis.

  `,
  `Etiam luctus diam viverra rutrum hendrerit. Aenean odio erat, cursus eget aliquet sed, mattis at lorem. Nam vitae malesuada neque, ac varius arcu. Sed urna nulla, efficitur ut leo eget, euismod accumsan mauris. Integer fringilla elit vel faucibus porta. Curabitur feugiat facilisis orci et porttitor. Fusce vitae sem neque. Sed blandit massa nec posuere tincidunt. Quisque ornare, ex ut ullamcorper mattis, turpis ligula lacinia arcu, at pellentesque velit eros vitae mauris.`,
  `Aenean maximus eleifend purus, in ultrices ante auctor in. Donec mollis quam sit amet sapien luctus aliquam. Fusce pretium laoreet purus tincidunt sollicitudin. Suspendisse rhoncus tellus tortor, ut varius mauris laoreet in. Proin nulla justo, mollis in lorem ut, porta porta odio. Maecenas ac accumsan nulla. Aliquam ligula dolor, tristique sed feugiat eget, dapibus eu metus. Vestibulum ut tincidunt augue, at dictum mi. Phasellus massa mi, rhoncus a iaculis quis, semper quis risus.`,
]

export default data
